export const types = Object.freeze({
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    ADD_PROFILE: 'ADD_PROFILE',
    ADD_CONTACTS: 'ADD_CONTACTS',
    UPDATE_IS_LOGGED: 'UPDATE_IS_LOGGED',
    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
});
